from . import pos_category
from . import product_category
from . import product_template
from . import res_partner
from . import stock_min_dates
from . import stock_count
from . import stock_warehouse_orderpoint
from . import res_users
from . import stock_warehouse
from . import pos_order_line_permissions
from . import product_pricelist
from . import sale_order_line
from . import pos_order_line
from . import account_move_line
