{
    "name": "Todo Pintura Administration",
    "summary": "Administración de Todo Pintura",
    "version": "19.0.1.0.0",
    "description": "Administración de Todo Pintura",
    "company": "Xtendoo",
    "website": "http://www.xtendoo.es",
    'depends': ['base', 'product', 'contacts', 'point_of_sale'],
    "license": "AGPL-3",
    "data": [
        'wizards/import_contacts_wizard_view.xml',
        'wizards/import_suppliers_wizard_view.xml',
        'wizards/import_products_wizard_view.xml',
        'wizards/import_categories_wizard_view.xml',
        'wizards/import_client_tariffs_wizard_view.xml',
        'wizards/import_stock_min_wizard_view.xml',
        'wizards/import_stock_in_hand_wizard_view.xml',
        'wizards/stock_count_wizard_view.xml',
        'wizards/stock_count_compare_views.xml',
        'views/menu.xml',
        'views/product_template.xml',
        'views/pos_category.xml',
        'views/product_category.xml',
        'views/product_pricelist_view_inherit.xml',
        'security/ir.model.access.csv',
        # 'views/res_partner_views.xml',
        'views/stock_orderpoint_views.xml',
        'views/stock_min_date_views.xml',
        'views/report_invoice_document_custom.xml',
        'views/report_delivery_document.xml',
        'views/stock_count.xml',
    ],
    "installable": True,
}
